KeyboardLayouts = { "English (US)" : "us",
                    "Afghani" : "af",
                    "Arabic" : "ara",
                    "Albanian" : "al",
                    "Armenian" : "am",
                    "German (Austria)" : "at",
                    "Azerbaijani" : "az",
                    "Belarusian" : "by",
                    "Belgian" : "be",
                    "Bangla" : "bd",
                    "Indian" : "in",
                    "Bosnian" : "ba",
                    "Portuguese (Brazil)" : "br",
                    "Bulgarian" : "bg",
                    "Arabic (Morocco)" : "ma",
                    "English (Cameroon)" : "cm",
                    "Burmese" : "mm",
                    "French (Canada)" : "ca",
                    "French (Democratic Republic of the Congo)" : "cd",
                    "Chinese" : "cn",
                    "Croatian" : "hr",
                    "Czech" : "cz",
                    "Danish" : "dk",
                    "Dutch" : "nl",
                    "Dzongkha" : "bt",
                    "Estonian" : "ee",
                    "Persian" : "ir",
                    "Iraqi" : "iq",
                    "Faroese" : "fo",
                    "Finnish" : "fi",
                    "French" : "fr",
                    "English (Ghana)" : "gh",
                    "French (Guinea)" : "gn",
                    "Georgian" : "ge",
                    "German" : "de",
                    "Greek" : "gr",
                    "Hungarian" : "hu",
                    "Icelandic" : "is",
                    "Hebrew" : "il",
                    "Italian" : "it",
                    "Japanese" : "jp",
                    "Kyrgyz" : "kg",
                    "Khmer (Cambodia)" : "kh",
                    "Kazakh" : "kz",
                    "Lao" : "la",
                    "Spanish (Latin American)" : "latam",
                    "Lithuanian" : "lt",
                    "Latvian" : "lv",
                    "Maori" : "mao",
                    "Montenegrin" : "me",
                    "Macedonian" : "mk",
                    "Maltese" : "mt",
                    "Mongolian" : "mn",
                    "Norwegian" : "no",
                    "Polish" : "pl",
                    "Portuguese" : "pt",
                    "Romanian" : "ro",
                    "Russian" : "ru",
                    "Serbian" : "rs",
                    "Slovenian" : "si",
                    "Slovak" : "sk",
                    "Spanish" : "es",
                    "Swedish" : "se",
                    "German (Switzerland)" : "ch",
                    "Arabic (Syria)" : "sy",
                    "Tajik" : "tj",
                    "Sinhala (phonetic)" : "lk",
                    "Thai" : "th",
                    "Turkish" : "tr",
                    "Taiwanese" : "tw",
                    "Ukrainian" : "ua",
                    "English (UK)" : "gb",
                    "Uzbek" : "uz",
                    "Vietnamese" : "vn",
                    "Korean" : "kr",
                    "Japanese (PC-98xx Series)" : "nec_vndr/jp",
                    "Irish" : "ie",
                    "Urdu (Pakistan)" : "pk",
                    "Dhivehi" : "mv",
                    "English (South Africa)" : "za",
                    "Esperanto" : "epo",
                    "Nepali" : "np",
                    "English (Nigeria)" : "ng",
                    "Amharic" : "et",
                    "Wolof" : "sn",
                    "Braille" : "brai",
                    "Turkmen" : "tm",
                    "Bambara" : "ml",
                    "Swahili (Tanzania)" : "tz",
                    "Swahili (Kenya)" : "ke",
                    "Tswana" : "bw",
                    "Filipino" : "ph",
                    "Moldavian" : "md" }
